

=pod

=head1 NAME

simo.el - simple image manupulation object.

=head1 SYNOPSIS

  (require 'simo)

  (let* ((w  64)
         (h  64)
         (hw (/ w 2))
         (hh (/ h 2))
         (img (simo::new :width w :height h)))
    (simo-fill-rect img 0 0  w  h 0)

    (simo-draw-line img 0 0  w hh 1)
    (simo-draw-line img 0 0  w  h 1)
    (simo-draw-line img 0 0 hw  h 1)

    (simo-draw-line img w 0  0 hh 2)
    (simo-draw-line img w 0  0  h 2)
    (simo-draw-line img w 0 hw  h 2)

    (simo-draw-line img w h  0 hh 3)
    (simo-draw-line img w h  0  0 3)
    (simo-draw-line img w h hw  0 3)

    (simo-draw-line img 0 h  w hh 4)
    (simo-draw-line img 0 h  w  0 4)
    (simo-draw-line img 0 h hw  0 4)

    (simo-rect      img 0 0  w  h 7)

    (let ((xpm (simo-to-xpm img)))
      (insert xpm "\n")
      (insert (simo::add-image-properties
               xpm
               :palette simo-alist-palette-16))
      (insert (simo::add-image-properties
               xpm
               :palette (simo-palette::list-to-alist
                         (reverse simo-list-palette-16))))
      (insert "\n")))


=head1 DESCRIPTION

"simo" provides simple manipulation method of images.

=head1 simo-palette

=head1 simo

=head2 (simo::new :width WIDTH :height HEIGHT)

=head2 (simo-resize SIMO WIDTH HEIGHT &optional X Y)

=head2 (simo-put-color SIMO X Y COLOR-NUM)

=head2 (simo-get-color SIMO X Y)

=head2 (simo-fill-rect SIMO X0 Y0 X1 Y1 COLOR-NUM)

=head2 (simo-rect SIMO X0 Y0 X1 Y1 COLOR-NUM)

=head2 (simo-draw-line X0 Y0 X1 Y1 COLOR-NUM)

=head1 AUTHOR

  lieutar <lieutar at 1dk.jp>

=cut
